version: '3'

services:
  app:
    image: docke-nextjs
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./prisma:/app/prisma
      - ./utils:/app/utils